// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/cayleygraph/quad/pquads/quads.proto

package pquads

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Quad is in internal representation of quad used by Cayley.
type Quad struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Predicate            string   `protobuf:"bytes,2,opt,name=predicate,proto3" json:"predicate,omitempty"`
	Object               string   `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	Label                string   `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	SubjectValue         *Value   `protobuf:"bytes,5,opt,name=subject_value,json=subjectValue,proto3" json:"subject_value,omitempty"`
	PredicateValue       *Value   `protobuf:"bytes,6,opt,name=predicate_value,json=predicateValue,proto3" json:"predicate_value,omitempty"`
	ObjectValue          *Value   `protobuf:"bytes,7,opt,name=object_value,json=objectValue,proto3" json:"object_value,omitempty"`
	LabelValue           *Value   `protobuf:"bytes,8,opt,name=label_value,json=labelValue,proto3" json:"label_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quad) Reset()         { *m = Quad{} }
func (m *Quad) String() string { return proto.CompactTextString(m) }
func (*Quad) ProtoMessage()    {}
func (*Quad) Descriptor() ([]byte, []int) {
	return fileDescriptor_71ac857d72b672e0, []int{0}
}

func (m *Quad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quad.Unmarshal(m, b)
}
func (m *Quad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quad.Marshal(b, m, deterministic)
}
func (m *Quad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quad.Merge(m, src)
}
func (m *Quad) XXX_Size() int {
	return xxx_messageInfo_Quad.Size(m)
}
func (m *Quad) XXX_DiscardUnknown() {
	xxx_messageInfo_Quad.DiscardUnknown(m)
}

var xxx_messageInfo_Quad proto.InternalMessageInfo

func (m *Quad) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Quad) GetPredicate() string {
	if m != nil {
		return m.Predicate
	}
	return ""
}

func (m *Quad) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *Quad) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Quad) GetSubjectValue() *Value {
	if m != nil {
		return m.SubjectValue
	}
	return nil
}

func (m *Quad) GetPredicateValue() *Value {
	if m != nil {
		return m.PredicateValue
	}
	return nil
}

func (m *Quad) GetObjectValue() *Value {
	if m != nil {
		return m.ObjectValue
	}
	return nil
}

func (m *Quad) GetLabelValue() *Value {
	if m != nil {
		return m.LabelValue
	}
	return nil
}

// WireQuad is a quad that allows any value for it's directions.
type WireQuad struct {
	Subject              *Value   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Predicate            *Value   `protobuf:"bytes,2,opt,name=predicate,proto3" json:"predicate,omitempty"`
	Object               *Value   `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	Label                *Value   `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WireQuad) Reset()         { *m = WireQuad{} }
func (m *WireQuad) String() string { return proto.CompactTextString(m) }
func (*WireQuad) ProtoMessage()    {}
func (*WireQuad) Descriptor() ([]byte, []int) {
	return fileDescriptor_71ac857d72b672e0, []int{1}
}

func (m *WireQuad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WireQuad.Unmarshal(m, b)
}
func (m *WireQuad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WireQuad.Marshal(b, m, deterministic)
}
func (m *WireQuad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WireQuad.Merge(m, src)
}
func (m *WireQuad) XXX_Size() int {
	return xxx_messageInfo_WireQuad.Size(m)
}
func (m *WireQuad) XXX_DiscardUnknown() {
	xxx_messageInfo_WireQuad.DiscardUnknown(m)
}

var xxx_messageInfo_WireQuad proto.InternalMessageInfo

func (m *WireQuad) GetSubject() *Value {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *WireQuad) GetPredicate() *Value {
	if m != nil {
		return m.Predicate
	}
	return nil
}

func (m *WireQuad) GetObject() *Value {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *WireQuad) GetLabel() *Value {
	if m != nil {
		return m.Label
	}
	return nil
}

// WireQuadRaw is the same as WireQuad, but doesn't decode underlying values.
type WireQuadRaw struct {
	Subject              []byte   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Predicate            []byte   `protobuf:"bytes,2,opt,name=predicate,proto3" json:"predicate,omitempty"`
	Object               []byte   `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	Label                []byte   `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WireQuadRaw) Reset()         { *m = WireQuadRaw{} }
func (m *WireQuadRaw) String() string { return proto.CompactTextString(m) }
func (*WireQuadRaw) ProtoMessage()    {}
func (*WireQuadRaw) Descriptor() ([]byte, []int) {
	return fileDescriptor_71ac857d72b672e0, []int{2}
}

func (m *WireQuadRaw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WireQuadRaw.Unmarshal(m, b)
}
func (m *WireQuadRaw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WireQuadRaw.Marshal(b, m, deterministic)
}
func (m *WireQuadRaw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WireQuadRaw.Merge(m, src)
}
func (m *WireQuadRaw) XXX_Size() int {
	return xxx_messageInfo_WireQuadRaw.Size(m)
}
func (m *WireQuadRaw) XXX_DiscardUnknown() {
	xxx_messageInfo_WireQuadRaw.DiscardUnknown(m)
}

var xxx_messageInfo_WireQuadRaw proto.InternalMessageInfo

func (m *WireQuadRaw) GetSubject() []byte {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *WireQuadRaw) GetPredicate() []byte {
	if m != nil {
		return m.Predicate
	}
	return nil
}

func (m *WireQuadRaw) GetObject() []byte {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *WireQuadRaw) GetLabel() []byte {
	if m != nil {
		return m.Label
	}
	return nil
}

// StrictQuad is a quad as described by RDF spec.
type StrictQuad struct {
	Subject              *StrictQuad_Ref `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Predicate            *StrictQuad_Ref `protobuf:"bytes,2,opt,name=predicate,proto3" json:"predicate,omitempty"`
	Object               *Value          `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	Label                *StrictQuad_Ref `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StrictQuad) Reset()         { *m = StrictQuad{} }
func (m *StrictQuad) String() string { return proto.CompactTextString(m) }
func (*StrictQuad) ProtoMessage()    {}
func (*StrictQuad) Descriptor() ([]byte, []int) {
	return fileDescriptor_71ac857d72b672e0, []int{3}
}

func (m *StrictQuad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrictQuad.Unmarshal(m, b)
}
func (m *StrictQuad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrictQuad.Marshal(b, m, deterministic)
}
func (m *StrictQuad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrictQuad.Merge(m, src)
}
func (m *StrictQuad) XXX_Size() int {
	return xxx_messageInfo_StrictQuad.Size(m)
}
func (m *StrictQuad) XXX_DiscardUnknown() {
	xxx_messageInfo_StrictQuad.DiscardUnknown(m)
}

var xxx_messageInfo_StrictQuad proto.InternalMessageInfo

func (m *StrictQuad) GetSubject() *StrictQuad_Ref {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *StrictQuad) GetPredicate() *StrictQuad_Ref {
	if m != nil {
		return m.Predicate
	}
	return nil
}

func (m *StrictQuad) GetObject() *Value {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *StrictQuad) GetLabel() *StrictQuad_Ref {
	if m != nil {
		return m.Label
	}
	return nil
}

type StrictQuad_Ref struct {
	// Types that are valid to be assigned to Value:
	//	*StrictQuad_Ref_BnodeLabel
	//	*StrictQuad_Ref_Iri
	Value                isStrictQuad_Ref_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StrictQuad_Ref) Reset()         { *m = StrictQuad_Ref{} }
func (m *StrictQuad_Ref) String() string { return proto.CompactTextString(m) }
func (*StrictQuad_Ref) ProtoMessage()    {}
func (*StrictQuad_Ref) Descriptor() ([]byte, []int) {
	return fileDescriptor_71ac857d72b672e0, []int{3, 0}
}

func (m *StrictQuad_Ref) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrictQuad_Ref.Unmarshal(m, b)
}
func (m *StrictQuad_Ref) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrictQuad_Ref.Marshal(b, m, deterministic)
}
func (m *StrictQuad_Ref) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrictQuad_Ref.Merge(m, src)
}
func (m *StrictQuad_Ref) XXX_Size() int {
	return xxx_messageInfo_StrictQuad_Ref.Size(m)
}
func (m *StrictQuad_Ref) XXX_DiscardUnknown() {
	xxx_messageInfo_StrictQuad_Ref.DiscardUnknown(m)
}

var xxx_messageInfo_StrictQuad_Ref proto.InternalMessageInfo

type isStrictQuad_Ref_Value interface {
	isStrictQuad_Ref_Value()
}

type StrictQuad_Ref_BnodeLabel struct {
	BnodeLabel string `protobuf:"bytes,2,opt,name=bnode_label,json=bnodeLabel,proto3,oneof"`
}

type StrictQuad_Ref_Iri struct {
	Iri string `protobuf:"bytes,3,opt,name=iri,proto3,oneof"`
}

func (*StrictQuad_Ref_BnodeLabel) isStrictQuad_Ref_Value() {}

func (*StrictQuad_Ref_Iri) isStrictQuad_Ref_Value() {}

func (m *StrictQuad_Ref) GetValue() isStrictQuad_Ref_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *StrictQuad_Ref) GetBnodeLabel() string {
	if x, ok := m.GetValue().(*StrictQuad_Ref_BnodeLabel); ok {
		return x.BnodeLabel
	}
	return ""
}

func (m *StrictQuad_Ref) GetIri() string {
	if x, ok := m.GetValue().(*StrictQuad_Ref_Iri); ok {
		return x.Iri
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StrictQuad_Ref) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StrictQuad_Ref_BnodeLabel)(nil),
		(*StrictQuad_Ref_Iri)(nil),
	}
}

// StrictQuadRaw is the same as StrictQuad, but doesn't decode underlying values.
type StrictQuadRaw struct {
	Subject              []byte   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Predicate            []byte   `protobuf:"bytes,2,opt,name=predicate,proto3" json:"predicate,omitempty"`
	Object               []byte   `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	Label                []byte   `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrictQuadRaw) Reset()         { *m = StrictQuadRaw{} }
func (m *StrictQuadRaw) String() string { return proto.CompactTextString(m) }
func (*StrictQuadRaw) ProtoMessage()    {}
func (*StrictQuadRaw) Descriptor() ([]byte, []int) {
	return fileDescriptor_71ac857d72b672e0, []int{4}
}

func (m *StrictQuadRaw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrictQuadRaw.Unmarshal(m, b)
}
func (m *StrictQuadRaw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrictQuadRaw.Marshal(b, m, deterministic)
}
func (m *StrictQuadRaw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrictQuadRaw.Merge(m, src)
}
func (m *StrictQuadRaw) XXX_Size() int {
	return xxx_messageInfo_StrictQuadRaw.Size(m)
}
func (m *StrictQuadRaw) XXX_DiscardUnknown() {
	xxx_messageInfo_StrictQuadRaw.DiscardUnknown(m)
}

var xxx_messageInfo_StrictQuadRaw proto.InternalMessageInfo

func (m *StrictQuadRaw) GetSubject() []byte {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *StrictQuadRaw) GetPredicate() []byte {
	if m != nil {
		return m.Predicate
	}
	return nil
}

func (m *StrictQuadRaw) GetObject() []byte {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *StrictQuadRaw) GetLabel() []byte {
	if m != nil {
		return m.Label
	}
	return nil
}

type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_Raw
	//	*Value_Str
	//	*Value_Iri
	//	*Value_Bnode
	//	*Value_TypedStr
	//	*Value_LangStr
	//	*Value_Int
	//	*Value_Float
	//	*Value_Boolean
	//	*Value_Time
	Value                isValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_71ac857d72b672e0, []int{5}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Value interface {
	isValue_Value()
}

type Value_Raw struct {
	Raw []byte `protobuf:"bytes,1,opt,name=raw,proto3,oneof"`
}

type Value_Str struct {
	Str string `protobuf:"bytes,2,opt,name=str,proto3,oneof"`
}

type Value_Iri struct {
	Iri string `protobuf:"bytes,3,opt,name=iri,proto3,oneof"`
}

type Value_Bnode struct {
	Bnode string `protobuf:"bytes,4,opt,name=bnode,proto3,oneof"`
}

type Value_TypedStr struct {
	TypedStr *Value_TypedString `protobuf:"bytes,5,opt,name=typed_str,json=typedStr,proto3,oneof"`
}

type Value_LangStr struct {
	LangStr *Value_LangString `protobuf:"bytes,6,opt,name=lang_str,json=langStr,proto3,oneof"`
}

type Value_Int struct {
	Int int64 `protobuf:"varint,7,opt,name=int,proto3,oneof"`
}

type Value_Float struct {
	Float float64 `protobuf:"fixed64,8,opt,name=float,proto3,oneof"`
}

type Value_Boolean struct {
	Boolean bool `protobuf:"varint,9,opt,name=boolean,proto3,oneof"`
}

type Value_Time struct {
	Time *Value_Timestamp `protobuf:"bytes,10,opt,name=time,proto3,oneof"`
}

func (*Value_Raw) isValue_Value() {}

func (*Value_Str) isValue_Value() {}

func (*Value_Iri) isValue_Value() {}

func (*Value_Bnode) isValue_Value() {}

func (*Value_TypedStr) isValue_Value() {}

func (*Value_LangStr) isValue_Value() {}

func (*Value_Int) isValue_Value() {}

func (*Value_Float) isValue_Value() {}

func (*Value_Boolean) isValue_Value() {}

func (*Value_Time) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetRaw() []byte {
	if x, ok := m.GetValue().(*Value_Raw); ok {
		return x.Raw
	}
	return nil
}

func (m *Value) GetStr() string {
	if x, ok := m.GetValue().(*Value_Str); ok {
		return x.Str
	}
	return ""
}

func (m *Value) GetIri() string {
	if x, ok := m.GetValue().(*Value_Iri); ok {
		return x.Iri
	}
	return ""
}

func (m *Value) GetBnode() string {
	if x, ok := m.GetValue().(*Value_Bnode); ok {
		return x.Bnode
	}
	return ""
}

func (m *Value) GetTypedStr() *Value_TypedString {
	if x, ok := m.GetValue().(*Value_TypedStr); ok {
		return x.TypedStr
	}
	return nil
}

func (m *Value) GetLangStr() *Value_LangString {
	if x, ok := m.GetValue().(*Value_LangStr); ok {
		return x.LangStr
	}
	return nil
}

func (m *Value) GetInt() int64 {
	if x, ok := m.GetValue().(*Value_Int); ok {
		return x.Int
	}
	return 0
}

func (m *Value) GetFloat() float64 {
	if x, ok := m.GetValue().(*Value_Float); ok {
		return x.Float
	}
	return 0
}

func (m *Value) GetBoolean() bool {
	if x, ok := m.GetValue().(*Value_Boolean); ok {
		return x.Boolean
	}
	return false
}

func (m *Value) GetTime() *Value_Timestamp {
	if x, ok := m.GetValue().(*Value_Time); ok {
		return x.Time
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_Raw)(nil),
		(*Value_Str)(nil),
		(*Value_Iri)(nil),
		(*Value_Bnode)(nil),
		(*Value_TypedStr)(nil),
		(*Value_LangStr)(nil),
		(*Value_Int)(nil),
		(*Value_Float)(nil),
		(*Value_Boolean)(nil),
		(*Value_Time)(nil),
	}
}

type Value_TypedString struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value_TypedString) Reset()         { *m = Value_TypedString{} }
func (m *Value_TypedString) String() string { return proto.CompactTextString(m) }
func (*Value_TypedString) ProtoMessage()    {}
func (*Value_TypedString) Descriptor() ([]byte, []int) {
	return fileDescriptor_71ac857d72b672e0, []int{5, 0}
}

func (m *Value_TypedString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value_TypedString.Unmarshal(m, b)
}
func (m *Value_TypedString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value_TypedString.Marshal(b, m, deterministic)
}
func (m *Value_TypedString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value_TypedString.Merge(m, src)
}
func (m *Value_TypedString) XXX_Size() int {
	return xxx_messageInfo_Value_TypedString.Size(m)
}
func (m *Value_TypedString) XXX_DiscardUnknown() {
	xxx_messageInfo_Value_TypedString.DiscardUnknown(m)
}

var xxx_messageInfo_Value_TypedString proto.InternalMessageInfo

func (m *Value_TypedString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Value_TypedString) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Value_LangString struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Lang                 string   `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value_LangString) Reset()         { *m = Value_LangString{} }
func (m *Value_LangString) String() string { return proto.CompactTextString(m) }
func (*Value_LangString) ProtoMessage()    {}
func (*Value_LangString) Descriptor() ([]byte, []int) {
	return fileDescriptor_71ac857d72b672e0, []int{5, 1}
}

func (m *Value_LangString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value_LangString.Unmarshal(m, b)
}
func (m *Value_LangString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value_LangString.Marshal(b, m, deterministic)
}
func (m *Value_LangString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value_LangString.Merge(m, src)
}
func (m *Value_LangString) XXX_Size() int {
	return xxx_messageInfo_Value_LangString.Size(m)
}
func (m *Value_LangString) XXX_DiscardUnknown() {
	xxx_messageInfo_Value_LangString.DiscardUnknown(m)
}

var xxx_messageInfo_Value_LangString proto.InternalMessageInfo

func (m *Value_LangString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Value_LangString) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

// From https://github.com/golang/protobuf/blob/master/ptypes/timestamp/timestamp.proto
type Value_Timestamp struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos                int32    `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value_Timestamp) Reset()         { *m = Value_Timestamp{} }
func (m *Value_Timestamp) String() string { return proto.CompactTextString(m) }
func (*Value_Timestamp) ProtoMessage()    {}
func (*Value_Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_71ac857d72b672e0, []int{5, 2}
}

func (m *Value_Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value_Timestamp.Unmarshal(m, b)
}
func (m *Value_Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value_Timestamp.Marshal(b, m, deterministic)
}
func (m *Value_Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value_Timestamp.Merge(m, src)
}
func (m *Value_Timestamp) XXX_Size() int {
	return xxx_messageInfo_Value_Timestamp.Size(m)
}
func (m *Value_Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Value_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Value_Timestamp proto.InternalMessageInfo

func (m *Value_Timestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Value_Timestamp) GetNanos() int32 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

type Header struct {
	// Full is set if encoder always writes every quad directions instead of
	// skipping duplicated values on each direction (except label) for subsequent quads.
	Full bool `protobuf:"varint,1,opt,name=full,proto3" json:"full,omitempty"`
	// NotStrict is set if encoder emits WireQuad instead of StrictQuad messages.
	NotStrict            bool     `protobuf:"varint,2,opt,name=not_strict,json=notStrict,proto3" json:"not_strict,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_71ac857d72b672e0, []int{6}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetFull() bool {
	if m != nil {
		return m.Full
	}
	return false
}

func (m *Header) GetNotStrict() bool {
	if m != nil {
		return m.NotStrict
	}
	return false
}

func init() {
	proto.RegisterType((*Quad)(nil), "pquads.Quad")
	proto.RegisterType((*WireQuad)(nil), "pquads.WireQuad")
	proto.RegisterType((*WireQuadRaw)(nil), "pquads.WireQuadRaw")
	proto.RegisterType((*StrictQuad)(nil), "pquads.StrictQuad")
	proto.RegisterType((*StrictQuad_Ref)(nil), "pquads.StrictQuad.Ref")
	proto.RegisterType((*StrictQuadRaw)(nil), "pquads.StrictQuadRaw")
	proto.RegisterType((*Value)(nil), "pquads.Value")
	proto.RegisterType((*Value_TypedString)(nil), "pquads.Value.TypedString")
	proto.RegisterType((*Value_LangString)(nil), "pquads.Value.LangString")
	proto.RegisterType((*Value_Timestamp)(nil), "pquads.Value.Timestamp")
	proto.RegisterType((*Header)(nil), "pquads.Header")
}

func init() {
	proto.RegisterFile("github.com/cayleygraph/quad/pquads/quads.proto", fileDescriptor_71ac857d72b672e0)
}

var fileDescriptor_71ac857d72b672e0 = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xcd, 0x6e, 0xd4, 0x3c,
	0x14, 0x9d, 0x4c, 0xe6, 0x27, 0x73, 0x93, 0x7e, 0x1f, 0xb2, 0x50, 0x09, 0x23, 0x90, 0xca, 0x20,
	0x44, 0x25, 0x20, 0xad, 0x0a, 0x14, 0xa4, 0xee, 0x58, 0x45, 0xd0, 0x0d, 0x06, 0xc1, 0xb2, 0x72,
	0x12, 0xcf, 0x34, 0x28, 0x63, 0x87, 0xc4, 0xa1, 0x9a, 0x17, 0xe1, 0x29, 0x78, 0x02, 0x1e, 0x8d,
	0x15, 0xf2, 0x75, 0x92, 0xf9, 0x47, 0x62, 0xc3, 0x66, 0xe4, 0x73, 0x7d, 0x8f, 0xef, 0xb9, 0xc7,
	0xbe, 0x19, 0x08, 0x66, 0xa9, 0xba, 0xae, 0xa2, 0x20, 0x96, 0xf3, 0x93, 0x98, 0x2d, 0x32, 0xbe,
	0x98, 0x15, 0x2c, 0xbf, 0x3e, 0xf9, 0x5a, 0xb1, 0xe4, 0x24, 0xd7, 0xbf, 0x25, 0xae, 0xcb, 0x20,
	0x2f, 0xa4, 0x92, 0x64, 0x60, 0x62, 0x93, 0x9f, 0x5d, 0xe8, 0xbd, 0xaf, 0x58, 0x42, 0x7c, 0x18,
	0x96, 0x55, 0xf4, 0x85, 0xc7, 0xca, 0xb7, 0x8e, 0xac, 0xe3, 0x11, 0x6d, 0x20, 0xb9, 0x07, 0xa3,
	0xbc, 0xe0, 0x49, 0x1a, 0x33, 0xc5, 0xfd, 0x2e, 0xee, 0x2d, 0x03, 0xe4, 0x10, 0x06, 0xd2, 0xd0,
	0x6c, 0xdc, 0xaa, 0x11, 0xb9, 0x0d, 0xfd, 0x8c, 0x45, 0x3c, 0xf3, 0x7b, 0x18, 0x36, 0x80, 0x9c,
	0xc1, 0x41, 0x7d, 0xec, 0xd5, 0x37, 0x96, 0x55, 0xdc, 0xef, 0x1f, 0x59, 0xc7, 0xee, 0xd9, 0x41,
	0x60, 0xe4, 0x04, 0x9f, 0x74, 0x90, 0x7a, 0x75, 0x0e, 0x22, 0x72, 0x0e, 0xff, 0xb7, 0xe5, 0x6a,
	0xd6, 0x60, 0x17, 0xeb, 0xbf, 0x36, 0xcb, 0xf0, 0x4e, 0xc1, 0x93, 0xab, 0xa5, 0x86, 0xbb, 0x48,
	0xae, 0x5c, 0xa9, 0x14, 0x80, 0x8b, 0x32, 0x6b, 0x82, 0xb3, 0x8b, 0x00, 0x98, 0x81, 0xeb, 0xc9,
	0x0f, 0x0b, 0x9c, 0xcf, 0x69, 0xc1, 0xd1, 0xc0, 0xc7, 0xeb, 0x06, 0x6e, 0x11, 0x5b, 0x3f, 0x9f,
	0x6c, 0xfa, 0xb9, 0x95, 0xba, 0x62, 0xef, 0xa3, 0x35, 0x7b, 0xb7, 0x32, 0x1b, 0xb7, 0x1f, 0xae,
	0xba, 0xbd, 0x95, 0x65, 0xf6, 0x26, 0x25, 0xb8, 0x8d, 0x5a, 0xca, 0x6e, 0x36, 0x6f, 0xdc, 0xfb,
	0xc3, 0x8d, 0x7b, 0xfb, 0x6f, 0xdc, 0xdb, 0x7d, 0xe3, 0x5e, 0x53, 0xf4, 0x7b, 0x17, 0xe0, 0x83,
	0x2a, 0xd2, 0x58, 0xa1, 0x4b, 0xa7, 0x9b, 0x2e, 0x1d, 0x36, 0x52, 0x97, 0x49, 0x01, 0xe5, 0xd3,
	0xa5, 0x98, 0x17, 0xdb, 0x76, 0xed, 0xe3, 0xfc, 0xbd, 0x6f, 0x4f, 0xd7, 0x7d, 0xdb, 0x77, 0xb0,
	0x49, 0x1a, 0xbf, 0x03, 0x9b, 0xf2, 0x29, 0x79, 0x00, 0x6e, 0x24, 0x64, 0xc2, 0xaf, 0x0c, 0x15,
	0x47, 0x22, 0xec, 0x50, 0xc0, 0xe0, 0x25, 0xbe, 0x73, 0x02, 0x76, 0x5a, 0xa4, 0x66, 0x24, 0xc2,
	0x0e, 0xd5, 0xe0, 0xcd, 0x10, 0xfa, 0xf8, 0xae, 0xde, 0xf6, 0x1c, 0xeb, 0x56, 0x77, 0x52, 0xc1,
	0xc1, 0xb2, 0xca, 0xbf, 0xbb, 0x8f, 0x5f, 0x36, 0xf4, 0xcd, 0x6b, 0x27, 0x60, 0x17, 0xec, 0xc6,
	0xd4, 0xd2, 0x1a, 0x0b, 0x76, 0xa3, 0x63, 0xa5, 0x2a, 0xda, 0x96, 0x34, 0xd8, 0xd5, 0x0b, 0x39,
	0x84, 0x3e, 0x76, 0x6b, 0xa6, 0x3b, 0xec, 0x50, 0x03, 0xc9, 0x6b, 0x18, 0xa9, 0x45, 0xce, 0x93,
	0x2b, 0x7d, 0x8a, 0x99, 0xed, 0xbb, 0x6b, 0xce, 0x07, 0x1f, 0xf5, 0xb6, 0x6e, 0x5c, 0xcc, 0xc2,
	0x0e, 0x75, 0x54, 0x0d, 0xc9, 0x4b, 0x70, 0x32, 0x26, 0x66, 0x48, 0x34, 0xe3, 0xed, 0xaf, 0x13,
	0x2f, 0x99, 0x98, 0xb5, 0xbc, 0x61, 0x66, 0x10, 0x8a, 0x13, 0x0a, 0x67, 0xdb, 0x46, 0x71, 0x42,
	0x69, 0x71, 0xd3, 0x4c, 0x32, 0x85, 0x03, 0x6c, 0x69, 0x71, 0x08, 0xc9, 0x18, 0x86, 0x91, 0x94,
	0x19, 0x67, 0xc2, 0x1f, 0x1d, 0x59, 0xc7, 0x8e, 0x3e, 0xa7, 0x0e, 0x90, 0x67, 0xd0, 0x53, 0xe9,
	0x9c, 0xfb, 0x80, 0xa5, 0xef, 0x6c, 0x68, 0x4e, 0xe7, 0xbc, 0x54, 0x6c, 0x9e, 0x87, 0x1d, 0x8a,
	0x69, 0xe3, 0x57, 0xe0, 0xae, 0x34, 0xa2, 0xad, 0x36, 0x9f, 0x0c, 0xf3, 0xe9, 0x34, 0x80, 0x10,
	0xe8, 0xe9, 0xf6, 0xea, 0x6f, 0x26, 0xae, 0xc7, 0xe7, 0x00, 0xcb, 0x46, 0xf6, 0xf3, 0x74, 0x7b,
	0x0d, 0x4f, 0xaf, 0xc7, 0x17, 0x30, 0x6a, 0x55, 0xe0, 0x4b, 0xe1, 0xb1, 0x14, 0x49, 0x89, 0x44,
	0x9b, 0x36, 0x50, 0x1f, 0x28, 0x98, 0x90, 0x25, 0x72, 0xfb, 0xd4, 0x80, 0xf6, 0xe5, 0x4d, 0x2e,
	0x60, 0x10, 0x72, 0x96, 0x70, 0xed, 0x5b, 0x6f, 0x5a, 0x65, 0x19, 0xf2, 0x1d, 0x8a, 0x6b, 0x72,
	0x1f, 0x40, 0x48, 0xa5, 0x6f, 0x20, 0x8d, 0x15, 0x9e, 0xe0, 0xd0, 0x91, 0x90, 0xca, 0x3c, 0xd3,
	0x68, 0x80, 0xff, 0x1c, 0xcf, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x67, 0xed, 0x94, 0x6b,
	0x06, 0x00, 0x00,
}
